//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RadixWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personas()
        {
            this.documentos = new HashSet<documentos>();
            this.pago = new HashSet<pago>();
            this.contratos = new HashSet<contratos>();
            this.login = new HashSet<login>();
        }
    
        public string Per_Rut { get; set; }
        public string Per_Nom { get; set; }
        public string Per_ApePat { get; set; }
        public string Per_ApeMat { get; set; }
        public Nullable<int> Per_CanDoc { get; set; }
        public int Car_Id { get; set; }
        public Nullable<int> FAsi_Id { get; set; }
        public string Per_Dir { get; set; }
        public int Nac_Id { get; set; }
        public string Per_Cod { get; set; }
        public int EC_Id { get; set; }
        public string Per_FNac { get; set; }
        public string Per_Tel { get; set; }
        public string Per_Suel { get; set; }
        public int TImp_Id { get; set; }
        public string Per_Sex { get; set; }
        public string Per_Bono { get; set; }
        public string Per_FechaInicio { get; set; }
        public string Per_FechaFin { get; set; }
        public string Per_Estado { get; set; }
        public string Per_Des { get; set; }
        public int Desc_Id { get; set; }
        public Nullable<int> Grup_Id { get; set; }
        public int THor_Id { get; set; }
    
        public virtual cargos cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos> documentos { get; set; }
        public virtual estadosciviles estadosciviles { get; set; }
        public virtual fichadescuentos fichadescuentos { get; set; }
        public virtual fichasasistencias fichasasistencias { get; set; }
        public virtual grupos grupos { get; set; }
        public virtual nacionalidades nacionalidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago> pago { get; set; }
        public virtual tiposhorasextras tiposhorasextras { get; set; }
        public virtual tipoimpuestos tipoimpuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratos> contratos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login> login { get; set; }
    }
}
